### ISSUE TITLE
Input is not properly sanitized when using ng-embed as a filter

### ISSUE THREAD

**Issue by tomekwszelaki** [ritz078/ngEmbed#13]
Hi, 

I've just tried using ng-embed in a project I'm working on and initialy it looked great, but then I tried sending `<script>alert('hi')</script>` as a message and to my surprise it actually executed the code! This is a huge vulnerability and I think it has to be patched up asap!

I've only tried it with the filter don't know if it reproduces for the directive use as well.

**Comment by ritz078** [comment]
Thanks for reporting. Will try to fix this asap.

**Comment by tomekwszelaki** [comment]
how about this? https://github.com/ritz078/ngEmbed/pull/15
