### ISSUE TITLE
Emoticons replace characters

### ISSUE THREAD

**Issue by mrchacon** [ritz078/ngEmbed#2]
Hi! I'm having trouble with plain characters rendering. When I try to use the filter embed to parse " :/ " for instance, the filter replace this characters and put an empty square showing nothing.

There's a way to fix this?

Thanks! @ritz078

**Comment by ritz078** [comment]
This happens when the fonts aren't loading somehow . Check you console. Are the fonts loading ?

**Comment by mrchacon** [comment]
Sure the css style sheet you provide is loaded correctly.

When the input is ": smile :" for instance the output is the correct emoticon. But if the input is ":)" like a smiley face the output is an empty square as a replacement .

Here's a screenshot of the problem.

![screen shot 2015-05-05 at 9 13 01 am](https://cloud.githubusercontent.com/assets/6330747/7475986/16d4a916-f308-11e4-81bc-de1eea71b5b3.png)

Thanks for your help @ritz078 !

**Comment by ritz078** [comment]
can you send the screenshot of the issue with the console open ? I really think that the fonts folder is not at the correct location. Are you using the latest version ?

**Comment by mrchacon** [comment]
Sure, here's the screenshot of the console. There're some error logs from another directives.

Yes, I'm using the latest version and the folder has a correct path.
What should be the output for ":)" @ritz078 ?

**Comment by ritz078** [comment]
is the app live .Can i see the code ? 
Heres the output of **:)**
![npm-debug](https://cloud.githubusercontent.com/assets/5389035/7477762/89defcac-f373-11e4-8fab-4cfcd7a1e057.png)

Have you checked the demo in the demo folder ? Maybe it can help you.

**Comment by ritz078** [comment]
@mrchacon has your issue been resolved ?

**Comment by mrchacon** [comment]
Yes I solved it!. The problem was in the font-family used for the icon html tag. In my project I use another font as default and was conflicted with ngEmbed emocticons font.

I had to change a few lines of the ng-embed.css in order to work as a different class for emoticons.

The changed lines are:
https://github.com/ritz078/ngEmbed/blob/master/src/ng-embed.css#L351
https://github.com/ritz078/ngEmbed/blob/master/src/ng-embed.js#L117

The class to not be in conflict is now embedicon-emoticon.

Thanks for all your help @ritz078 ! Great contribution!

**Comment by ritz078** [comment]
Glad that you were able to fix the issue :+1:

**Comment by mardo** [comment]
Hi @ritz078, the conflicting library was fontawesome, many projects use this. I think it would be wise to use embedicon-emoticon instead of icon-emoticon :)

**Comment by ritz078** [comment]
@mardo @mrchacon fixed the conflict issue :)
