### ISSUE TITLE
Hide twitter text and only keep tweets ?

### ISSUE THREAD

**Issue by hugsbrugs** [ritz078/ngEmbed#20]
Hi and thanks for your great plugin !

I can obviously see the interest of displaying tweets under a block of text but what if I only want to display tweets and not the text ? I can't find an option to achieve this : is there one I've missed ?

Otherwise, would you have any advise to achieve this :  template ?

Hugo

**Comment by hugsbrugs** [comment]
ok got it just after asking ...

template option

``` javascript
embed-template-url="twitter-embed.html"
```

twitter-embed.html

``` html
<!-- <div ng-bind-html="neText"></div> -->

<div ng-if="tweets" ng-repeat="tweet in tweets">
    <div class="col-xs-12 col-sm-6" ng-bind-html="tweet"></div>
</div>
```

**Comment by ritz078** [comment]
Glad that you found it. :)
