### ISSUE TITLE
Multiple youtube channel

### ISSUE THREAD

**Issue by abdallahmayuto** [ritz078/ngEmbed#21]
Hello there,

Is it possible to pull youtube videos from different youtube channel more than once?

**Comment by ritz078** [comment]
It all depends on the url. Only if they are different.

**Comment by abdallahmayuto** [comment]
Actually what I'm asking is if it is possible to fetch videos from different youtube channels using the youtube api v3
thanks

**Comment by ritz078** [comment]
Your question is still not clear.

**Comment by abdallahmayuto** [comment]
Ok let me put it in these words, I want to load several videos from a specific youtube channel using Youtube API V3, is that possible with your product?

**Comment by ritz078** [comment]
No that is not supported.
