### ISSUE TITLE
Website links preview

### ISSUE THREAD

**Issue by rkimaoui** [ritz078/ngEmbed#22]
Hello there,

Thx for this great directive ! You've done a good job.

Website links preview will be a great addition (like in facebook and linkedin).

Could you please add it in the next release ? :smile:

**Comment by ritz078** [comment]
That is a tricky thing to do as you can directly get a website's data . You also need a backend for that.

**Comment by tomalex0** [comment]
I'm trying to implement link preview using http://embed.ly/ or similar API. Can this  logic be added as a plugin to existing code or do i need to change the base code itself?

**Comment by ritz078** [comment]
currently its not supported. you can check [embed.js](https://github.com/ritz078/embed.js) instead for opengraph API support
