### ISSUE TITLE
TypeError: Object neText has no method 'push at Function.H.$$addBindingInfo lib/angular/angular.min.js:72:449

### ISSUE THREAD

**Issue by serenearrow** [ritz078/ngEmbed#34]
Using the directive in ng-repeat and passing $scope variables like below:

`<ng-embed embed-data="othersPosts[$index]['content']"  embed-options="options"></ng-embed>`

$scope variables are defined in controller like so:
`$scope.othersPosts = []; //dynamically populated array for ng-repeat`
`$scope.options = {
      'linkTarget': '_blank'
  };`

 Also getting ReferenceError: hlsj Highlight JS is not defined

Any pointers what I may be doing wrong are welcome, thanks.

**Comment by ritz078** [comment]
when `$scope.otherPosts=[]` then `othersPosts[$index]['content']` will throw an error because you are trying to get content of undefined. make sure ng-embed is executed only after your dynamic data is populated. you may use `ng-if`

**Comment by serenearrow** [comment]
This is great, thanks a bunch
