### ISSUE TITLE
hide text if only a url to an image is posted

### ISSUE THREAD

**Issue by seiyria** [ritz078/ngEmbed#38]
Is this possible? Basically, I want to only show the image if the string passed into ng-embed is just a link to an image. I'm not sure how/if it's possible to get what ng-embed parses out, but I imagine hiding the text would be pretty easy

**Comment by seiyria** [comment]
I managed to resolve this with CSS.

**Comment by bettysteger** [comment]
I did it like that: **Hides link to file, if it is not just the link!**

```
ng-embed > div:first-child:not(:last-child) {
  display: none;
}
```
