### ISSUE TITLE
Get YouTube video details return 401 if you have "Authorization" header set prior

### ISSUE THREAD

**Issue by l3utterfly** [ritz078/ngEmbed#40]
If you are using your own authorization system:

It is a common scenario where you set common headers using Angular's $http service, i.e. `http.defaults.headers.common.Authorization = 'Basic YmVlcDpib29w'`.

However, the YouTube API will read that header incorrectly and always return 401 even if you have the right API key.

Fix, change line 377 to:
`$http.get('https://www.googleapis.com/youtube/v3/videos?id=' + RegExp.$1 + '&key=' + options.gdevAuth + '&part=snippet,statistics', {
                                        headers: { 'Authorization': undefined }      // clear existing headers if present for this http request
                                    })` 

This clears the Authorization header for the YouTube video detail request only since the YouTube video details endpoint does not require an Authorization header anyway, fixing the problem.

**Comment by robman87** [comment]
Thank you @l3utterfly and @sischnei.

**Comment by tdanielcox** [comment]
@robman87 This appears to be the case with vimeo as well

**Comment by robman87** [comment]
Fixed, thank you @tdanielcox :)
