### ISSUE TITLE
Embed Twitch HTML5 player instead of Flash

### ISSUE THREAD

**Issue by EternallLight** [ritz078/ngEmbed#54]
Twitch.tv gave up on using flash a while ago in flavor of HTML5. I couldn't use embedded flash player on Ubuntu. Probably it's time for ng-enbed to move to HTML player as well.
https://dev.twitch.tv/docs/embed-video
I already updated the code. Please accept my pull request to merge.

**Comment by robman87** [comment]
Merged your code, thank you for you contribution @EternallLight :)

**Comment by EternallLight** [comment]
Great! I'm happy to help.
