### ISSUE TITLE
Linkify “www.”

### ISSUE THREAD

**Issue by rubenswieringa** [ritz078/ngEmbed#6]
It would be cool if ng-embed would (optionally) turn words starting with “www.” into anchors. I wouldn't mind implementing it myself. Any thoughts on this matter?

**Comment by ritz078** [comment]
PR is welcome :+1:

**Comment by ritz078** [comment]
Hi @rubenswieringa ,
Any updates ?

**Comment by rubenswieringa** [comment]
Hey @ritz078,

Yes, sorry, I got sidetracked. I couldn't find any tests/specs, is that correct?

**Comment by rubenswieringa** [comment]
Also, what is the purpose of the `(href|src)=["']` part in urlRegex?

``` javascript
var urlRegex = /((href|src)=["']|)(\b(https?|ftp|file):\/\/[-A-Z0-9+()&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
```

**Comment by rubenswieringa** [comment]
Here's a PR:
[Turns URLs starting with 'www.' into links](https://github.com/ritz078/ngEmbed/pull/8)
