### ISSUE TITLE
ng-embed and unicode emije

### ISSUE THREAD

**Issue by mabuonomo** [ritz078/ngEmbed#94]
Hi,

ng-embed does not convert emoji from unicode format? (works only with shortcodes emoji?

Example: https://emojipedia.org/face-screaming-in-fear/
Shortcodes: :scream: :scream.:
Codepoints (unicode) U+1F631

**Comment by robman87** [comment]
Yes, only basic emojis like :) ^_^ etc and shortcodes. The browser should handle unicode I guess.
