### ISSUE TITLE
Regarding an emoji picker

### ISSUE THREAD

**Issue by kunchamharsha** [ritz078/ngEmbed#97]
Hey,
Thanks for the great plugin but was wondering how would we pick those emojis, i couldnt see any documentation for emoji pickers.

**Comment by robman87** [comment]
This project only parses text and replaces some text-snippets with images of smilies and emojis, converts plain text urls to <a> link elements etc. It doesn't have any picker built in. You can use an external picker that inserts text such as :), ^_^ etc that this project can replace with an image.

**Comment by kunchamharsha** [comment]
understood thanks
